version: '2'

services:
  discovery-service:
    build: .
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_DISCOVERY_HOST=discovery
    networks:
      - ecomm

networks:
  ecomm:
    external: true
    name: ecommerce-network