export const healthListData = [
  { id: 1, name: "바벨 백스쿼트", icon: "/health/바벨 백스쿼트.png" },
  { id: 2, name: "프론트 스쿼트", icon: "/health/프론트 스쿼트.png" },
  { id: 3, name: "덤벨 스플릿 스쿼트", icon: "/health/덤벨 스플릿 스쿼트.png" },
  {
    id: 4,
    name: "바벨 불가리안 스플릿 스쿼트",
    icon: "/health/바벨 불가리안 스플릿 스쿼트.png",
  },
  {
    id: 5,
    name: "루마니안 데드리프트",
    icon: "/health/루마니안 데드리프트.png",
  },
  { id: 6, name: "스모 데드리프트", icon: "/health/스모 데드리프트.png" },
  {
    id: 7,
    name: "컨벤셔널 데드리프트",
    icon: "/health/컨벤셔널 데드리프트.png",
  },
  { id: 8, name: "레그 컬", icon: "/health/레그 컬.png" },
  { id: 9, name: "레그 프레스", icon: "/health/레그 프레스.png" },
  { id: 10, name: "런지", icon: "/health/런지.png" },
  { id: 11, name: "바벨 런지", icon: "/health/바벨 런지.png" },
  { id: 12, name: "힙 쓰러스트", icon: "/health/힙 쓰러스트.png" },
  { id: 13, name: "벤치프레스", icon: "/health/벤치프레스.png" },
  {
    id: 14,
    name: "인클라인 벤치프레스",
    icon: "/health/인클라인 벤치프레스.png",
  },
  { id: 15, name: "덤벨 벤치프레스", icon: "/health/덤벨 벤치프레스.png" },
  { id: 16, name: "딥스", icon: "/health/딥스.png" },
  { id: 17, name: "덤벨 플라이", icon: "/health/덤벨 플라이.png" },
  { id: 19, name: "푸시업", icon: "/health/푸시업.png" },
  {
    id: 20,
    name: "스미스머신 벤치프레스",
    icon: "/health/스미스머신 벤치프레스.png",
  },
  {
    id: 21,
    name: "바벨 플로어 프레스",
    icon: "/health/바벨 플로어 프레스.png",
  },
  {
    id: 22,
    name: "스탠딩 케이블 플라이",
    icon: "/health/스탠딩 케이블 플라이.png",
  },
  { id: 23, name: "풀업", icon: "/health/풀업.png" },
  { id: 24, name: "친업", icon: "/health/친업.png" },
  { id: 25, name: "로우 로우 머신", icon: "/health/로우 로우 머신.png" },
  { id: 26, name: "하이 로우 머신", icon: "/health/하이 로우 머신.png" },
  { id: 30, name: "바벨 풀오버", icon: "/health/바벨 풀오버.png" },
  { id: 31, name: "랫풀다운", icon: "/health/랫풀다운.png" },
  { id: 32, name: "케이블 암 풀다운", icon: "/health/케이블 암 풀다운.png" },
  { id: 33, name: "오버헤드 프레스", icon: "/health/오버헤드 프레스.png" },
  { id: 34, name: "덤벨 숄더 프레스", icon: "/health/덤벨 숄더 프레스.png" },
  { id: 35, name: "숄더 프레스 머신", icon: "/health/숄더 프레스 머신.png" },
  {
    id: 36,
    name: "덤벨 레터럴 레이즈",
    icon: "/health/덤벨 레터럴 레이즈.png",
  },
  { id: 37, name: "바벨 슈러그", icon: "/health/바벨 슈러그.png" },
  { id: 38, name: "페이스 풀", icon: "/health/페이스 풀.png" },
  { id: 39, name: "푸시 프레스", icon: "/health/푸시 프레스.png" },
  {
    id: 40,
    name: "시티드 덤벨 리어 레터럴 레이즈",
    icon: "/health/시티드 덤벨 리어 레터럴 레이즈.png",
  },
  { id: 41, name: "슈러그 머신", icon: "/health/슈러그 머신.png" },
  { id: 42, name: "바벨 컬", icon: "/health/바벨 컬.png" },
  { id: 43, name: "이지바 컬", icon: "/health/이지바 컬.png" },
  { id: 44, name: "덤벨 컬", icon: "/health/덤벨 컬.png" },
  { id: 45, name: "덤벨 해머 컬", icon: "/health/덤벨 해머 컬.png" },
  {
    id: 46,
    name: "덤벨 트라이셉 익스텐션",
    icon: "/health/덤벨 트라이셉 익스텐션.png",
  },
  { id: 47, name: "덤벨 킥백", icon: "/health/덤벨 킥백.png" },
  { id: 48, name: "바벨 리스트 컬", icon: "/health/바벨 리스트 컬.png" },
  { id: 49, name: "벤치 딥스", icon: "/health/벤치 딥스.png" },
  {
    id: 50,
    name: "트라이셉 익스텐션 머신",
    icon: "/health/트라이셉 익스텐션 머신.png",
  },
];
