server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DoctorForU/ConfigFileRepo # ??? public??? ?? ????
          default-label: main
        bootstrap: true
#          username: [your username]
#          password: [your password]

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, metrics